### ISSUE TITLE
Corrupted file

### ISSUE THREAD

**Issue by AbreuDan** [PacktPublishing/Dynamics-365-for-Finance-and-Operations-Development-Cookbook-Fourth-Edition#1]
The file is zero bytes, please check the other files as well.

**Comment by MurtazaTinwala** [comment]
Hi @AbreuDan 

Sorry for the late reply!
Could you let me know which specific file is zero bytes in size?
The code files look fine to me. 
In case if there are any issues to the codes, I would update them.

Regards,

**Comment by githubce** [comment]
Closing as no reply from the user.
You may open this if the issue still persists.

Regards,
